### ISSUE TITLE
Show warning when attempting to verify production action

### ISSUE THREAD

**Issue by paolodamico** [worldcoin/simulator#70]
The simulator should only be used for actions on the **Staging network.** Now that we check the Developer Portal for metadata (after #68 is merged), with the retrieved metadata we should show a clear warning in the app if you attempt to verify a production action, directing you to the Worldcoin app instead.

@tino-otto feel free to reassign, let's just get to it by Thursday, please check with Dom for design on this.

**Comment by maxpetretta** [comment]
Fixed in https://github.com/worldcoin/simulator/pull/152
